### ISSUE TITLE
Un nouveau parseur?

### ISSUE THREAD

**Issue by quent1-fr** [Simple-chez-tuxfamily/Simple-RSS-Reader#11]
Je viens de tomber sur ce parseur PHP: il est _beaucoup_ plus léger que SimplePie. Si vous avez une opposition à son utilisation, dites le moi.
http://www.milletmaxime.net/142510-php-class-syndexport-parser-flux-atom-et-flux-rss.html

**Comment by Debetux** [comment]
Il sera bien plus léger.
C'est parfait pour l'utilisation de SRR !
